### ISSUE TITLE
Noob Owner

### ISSUE THREAD

**Issue by InfernoDrag0** [InfernoDragon0/XDreamerSEA-Maple#1]
Owner is a noob, and i think the items he is wearing is bugged, resulting in noobness

Bugged as in: Modified Illegally as said in the supposed rules.

**Comment by InfernoDragon0** [comment]
Owners do NOT wear custom items around other players at all times. Please do not spam on Github as we can report this to the officials.

**Comment by InfernoDragon0** [comment]
And I would add on that you are responsible to update your files according to the server's versions. This is also done automatically via the smart launcher which you are supposed to launch the game by.
